<h3 style="float:right">Makhmudov M</h3>

# Linear Algebra (basic)

In [5]:
#import module numpy
import numpy as np

### matrix initialization

In [18]:
m1 = np.matrix([[5,2,8],[9,2,-1],[8,3,1]])

In [19]:
print(m1)

[[ 5  2  8]
 [ 9  2 -1]
 [ 8  3  1]]


In [20]:
np.linalg.det(m1)

79.0