<h3 align=right>Makhmudov M</h3>

# MATRIX

In [6]:
import numpy as np

<hr>

### Matrix init

In [7]:
m1 = np.matrix([[1,2,3],[5,4,0]])
print(m1)

[[1 2 3]
 [5 4 0]]


In [8]:
m2 = np.matrix([[8,2,9], [19,3,-1]])
print(m2)

[[ 8  2  9]
 [19  3 -1]]


<hr>

### Matrix operation

#### addition

In [19]:
print("m1:",m1)
print("+")
print("m2:",m2)
print("=")
print(m1+m2)

m1: [[1 2 3]
 [5 4 0]]
+
m2: [[ 8  2  9]
 [19  3 -1]]
=
[[ 9  4 12]
 [24  7 -1]]


#### subtraction

In [11]:
print("m1:",m1)
print("-")
print("m2:",m2)
print("=")
print(m1-m2)

m1: [[1 2 3]
 [5 4 0]]
-
m2: [[ 8  2  9]
 [19  3 -1]]
=
[[ -7   0  -6]
 [-14   1   1]]


#### multiplication by a constant

In [13]:
print(m1)
4*m1

[[1 2 3]
 [5 4 0]]


matrix([[ 4,  8, 12],
        [20, 16,  0]])

#### matrix sum

In [16]:
m1.sum()

15

In [18]:
m1.sum() * m1

matrix([[15, 30, 45],
        [75, 60,  0]])